Use ArtExhibitionsDB
go
INSERT INTO Galleries VALUES (1, 'Mrs. John', 'Australia', 'BER', 'F0O8GF1#h7');
INSERT INTO Galleries VALUES (2, ' David', 'Australia', 'LON', '8B^8EGBSk%');
INSERT INTO Galleries VALUES (3, 'Mr. Emily', 'America', 'SYD', 'tDC!kXiUff');
INSERT INTO Galleries VALUES (4, 'Ms. Alice', 'India', 'TYO', 'rqtcs#0&L7');
INSERT INTO Galleries VALUES (5, 'Ms. Sophia', 'Japan', 'Dubai', 'N#XT8FU34A');
INSERT INTO Galleries VALUES (6, 'Mrs. Sophia', 'USA', 'NYC', 'cFK4g8wvs$');
INSERT INTO Galleries VALUES (7, 'Dr. Olivia', 'DownUnder', 'Berlin', 'YCK5d2!%EK');
INSERT INTO Galleries VALUES (8, ' Michael', 'UK', 'Berlin', 'Go1xCRpzjV');
INSERT INTO Galleries VALUES (9, 'Ms. Robert', 'Deutschland', 'PAR', 'V&cM 4&vF1');
INSERT INTO Galleries VALUES (10, 'Mr. Michael', 'USA', 'Berlin', 'HZ%*wjCqsz');
INSERT INTO Galleries VALUES (11, 'Mr. Emily', 'USA', 'DBX', 'olIDyigxy ');
INSERT INTO Galleries VALUES (12, 'Ms. John', 'UAE', 'BOM', 'NNceSIR2kB');
INSERT INTO Galleries VALUES (13, 'Mrs. Emily', 'France', 'London', '$GtFJ$%sEA');
INSERT INTO Galleries VALUES (14, 'Dr. Emily', 'Nippon', 'Sydney', ' JB#a0W#e2');
INSERT INTO Galleries VALUES (15, 'Mrs. David', 'Britain', 'Dubai', 'JbZ8$gIlCP');
INSERT INTO Galleries VALUES (16, 'Mr. David', 'UAE', 'BOM', 'Ch5qIFXZkX');
INSERT INTO Galleries VALUES (17, 'Ms. Alice', 'Britain', 'Sydney', 'Om8HQkb9P@');
INSERT INTO Galleries VALUES (18, 'Ms. Michael', 'Australia', 'Sydney', '#q#5EYbS6n');
INSERT INTO Galleries VALUES (19, 'Mrs. Sophia', 'India', 'LON', 'BK$fT@ZLlj');
INSERT INTO Galleries VALUES (20, 'Mrs. Alice', 'America', 'PAR', 'IXPKg^nOzJ');
INSERT INTO Galleries VALUES (21, 'Mr. Alice', 'Nippon', 'BOM', '@$ZGTQK 9*');
INSERT INTO Galleries VALUES (22, 'Dr. David', 'Germany', 'Tokyo', 'ejlA2LztOh');
INSERT INTO Galleries VALUES (23, 'Ms. Olivia', 'DownUnder', 'New York', 'lUZv2y$Lfj');
INSERT INTO Galleries VALUES (24, 'Mrs. Olivia', 'Japan', 'TYO', 'I4X2G!U*SL');
INSERT INTO Galleries VALUES (25, 'Mr. David', 'Deutschland', 'Mumbai', 'JLnJZaQ6Py');
INSERT INTO Galleries VALUES (26, 'Mrs. Alice', 'UAE', 'Dubai', 'X^a R99GrJ');
INSERT INTO Galleries VALUES (27, 'Mr. Alice', 'India', 'New York', 'w*s!oTuSow');
INSERT INTO Galleries VALUES (28, 'Mr. John', 'America', 'DBX', 'nsoa1Cjg8r');
INSERT INTO Galleries VALUES (29, ' Olivia', 'Germany', 'Mumbai', 'DKm$yf&qMN');
INSERT INTO Galleries VALUES (30, 'Ms. Michael', 'India', 'SYD', '9e0wJrH2NG');
INSERT INTO Galleries VALUES (31, ' Robert', 'Germany', 'New York', '$WAd*RUdFs');
INSERT INTO Galleries VALUES (32, 'Mrs. Michael', 'DownUnder', 'Tokyo', 'su0##muCtW');
INSERT INTO Galleries VALUES (33, 'Dr. Olivia', 'DownUnder', 'Paris', 'N*cvmBNuMJ');
INSERT INTO Galleries VALUES (34, 'Mrs. Robert', 'France', 'Dubai', 'ikcGpq1z#w');
INSERT INTO Galleries VALUES (35, 'Mr. Alice', 'DownUnder', 'Mumbai', 'q^3cUqS1Ik');
INSERT INTO Galleries VALUES (36, 'Ms. John', 'UK', 'New York', 'ZLi rLAmJz');
INSERT INTO Galleries VALUES (37, ' David', 'Japan', 'Tokyo', 'C$swDZSrVg');
INSERT INTO Galleries VALUES (38, 'Mrs. David', 'Deutschland', 'LON', 'MYT#Ah3Rh$');
INSERT INTO Galleries VALUES (39, 'Mr. Sophia', 'Nippon', 'New York', '$tHx%C5U!h');
INSERT INTO Galleries VALUES (40, 'Ms. Michael', 'Germany', 'BER', 'MpRj4d#JRK');
INSERT INTO Galleries VALUES (41, 'Ms. Olivia', 'France', 'Paris', 'XtoA&OLSYZ');
INSERT INTO Galleries VALUES (42, 'Mr. Emily', 'UAE', 'TYO', 'y2h0BoUN85');
INSERT INTO Galleries VALUES (43, 'Dr. Olivia', 'Britain', 'Sydney', '6icIB$N*!u');
INSERT INTO Galleries VALUES (44, 'Dr. Alice', 'Australia', 'Tokyo', 'ot%D&8VATR');
INSERT INTO Galleries VALUES (45, 'Dr. David', 'Britain', 'Paris', 'NBMgD!s!w5');
INSERT INTO Galleries VALUES (46, 'Ms. John', 'Japan', 'Sydney', 'VXn6^F8Nf^');
INSERT INTO Galleries VALUES (47, 'Dr. Michael', 'France', 'Paris', 'k0es$vj!hj');
INSERT INTO Galleries VALUES (48, 'Mrs. David', 'Deutschland', 'DBX', 'ewwIH20Vyd');
INSERT INTO Galleries VALUES (49, ' Olivia', 'DownUnder', 'PAR', 'C0$0FQQCS9');
INSERT INTO Galleries VALUES (50, 'Mrs. Robert', 'UK', 'London', 'PfbtSYZml9');
INSERT INTO Galleries VALUES (51, 'Ms. Olivia', 'UAE', 'SYD', 'v*GSVIqZ*^');
INSERT INTO Galleries VALUES (52, 'Ms. Robert', 'Deutschland', 'TYO', '6uni8G%%9%');
INSERT INTO Galleries VALUES (53, ' Sophia', 'Emirates', 'LON', 'fUnkCJOa#P');
INSERT INTO Galleries VALUES (54, 'Mr. Emily', 'Deutschland', 'BOM', '%UJ!OzCY#T');
INSERT INTO Galleries VALUES (55, 'Mr. Michael', 'Japan', 'NYC', 'Px*@Ymo$p^');
INSERT INTO Galleries VALUES (56, ' Emily', 'France', 'Tokyo', '@bRRH%RP6k');
INSERT INTO Galleries VALUES (57, 'Dr. Michael', 'India', 'BER', 'KIV9myma%P');
INSERT INTO Galleries VALUES (58, 'Dr. Michael', 'Australia', 'DBX', 'gD!04Xxr^t');
INSERT INTO Galleries VALUES (59, 'Mr. Michael', 'USA', 'Tokyo', 'RaZDbki&8S');
INSERT INTO Galleries VALUES (60, 'Mrs. Alice', 'Germany', 'BER', 'kEnAG%AVyZ');
INSERT INTO Galleries VALUES (61, 'Ms. David', 'France', 'NYC', 'JZFJPDDumv');
INSERT INTO Galleries VALUES (62, 'Mr. Michael', 'DownUnder', 'LON', 'aNVt77%nw4');
INSERT INTO Galleries VALUES (63, 'Dr. John', 'Britain', 'LON', 's!0Lj*qOoT');
INSERT INTO Galleries VALUES (64, 'Mrs. Sophia', 'Britain', 'New York', '4EHWd8xUqK');
INSERT INTO Galleries VALUES (65, 'Dr. Sophia', 'UK', 'SYD', 'StYs60Xt#q');
INSERT INTO Galleries VALUES (66, 'Mr. Alice', 'India', 'TYO', '21EsQ!JSOa');
INSERT INTO Galleries VALUES (67, 'Mr. Olivia', 'India', 'TYO', 'oL1mWxflhA');
INSERT INTO Galleries VALUES (68, 'Mr. Robert', 'India', 'LON', 'hzb2WtLHj!');
INSERT INTO Galleries VALUES (69, 'Mrs. John', 'Germany', 'Dubai', '7&aqL4K7Lw');
INSERT INTO Galleries VALUES (70, 'Ms. Alice', 'India', 'DBX', '5&EDrV^9IF');
INSERT INTO Galleries VALUES (71, 'Mr. David', 'Australia', 'BOM', 'j*N#hQEE#V');
INSERT INTO Galleries VALUES (72, 'Mr. Olivia', 'Britain', 'DBX', 'PaB Una&BZ');
INSERT INTO Galleries VALUES (73, 'Mr. Sophia', 'Australia', 'PAR', 'eP1bQb@u4U');
INSERT INTO Galleries VALUES (74, 'Mrs. Alice', 'UK', 'London', '7 oyQ0^NnS');
INSERT INTO Galleries VALUES (75, ' Robert', 'America', 'TYO', 'X9WoPsN8qa');
INSERT INTO Galleries VALUES (76, 'Mrs. David', 'Nippon', 'BER', '1zHGP2cdw$');
INSERT INTO Galleries VALUES (77, 'Dr. David', 'Deutschland', 'PAR', 'Whq!K&UCPG');
INSERT INTO Galleries VALUES (78, 'Dr. Sophia', 'DownUnder', 'PAR', '%M3ImUposK');
INSERT INTO Galleries VALUES (79, 'Mrs. Olivia', 'Deutschland', 'TYO', 'qBZLpM2PWM');
INSERT INTO Galleries VALUES (80, 'Ms. Sophia', 'America', 'SYD', 'Rb2OO68Hpr');
INSERT INTO Galleries VALUES (81, 'Ms. Alice', 'America', 'TYO', 'IIrefl78rB');
INSERT INTO Galleries VALUES (82, 'Mrs. Michael', 'Germany', 'Mumbai', 'ordVT9ZGvT');
INSERT INTO Galleries VALUES (83, 'Mr. Robert', 'DownUnder', 'DBX', '^T4P8q$ oG');
INSERT INTO Galleries VALUES (84, 'Dr. Robert', 'Australia', 'Sydney', 'g1khszK!1T');
INSERT INTO Galleries VALUES (85, 'Ms. Olivia', 'Emirates', 'Berlin', 'H7rDk4AJ$S');
INSERT INTO Galleries VALUES (86, 'Mr. David', 'America', 'BER', 'EMwNpt3BF0');
INSERT INTO Galleries VALUES (87, ' Robert', 'France', 'BER', '9lj2$xOw^c');
INSERT INTO Galleries VALUES (88, 'Mr. Michael', 'India', 'TYO', 'Mexh%QPkqQ');
INSERT INTO Galleries VALUES (89, 'Dr. Sophia', 'UAE', 'BOM', 'uvzQhqfRq9');
INSERT INTO Galleries VALUES (90, ' Robert', 'UAE', 'BER', 'iyAQ**!UtO');
INSERT INTO Galleries VALUES (91, 'Mrs. Alice', 'America', 'New York', 'FJloMf8u9N');
INSERT INTO Galleries VALUES (92, ' John', 'Deutschland', 'Berlin', '!gIFnNCI1F');
INSERT INTO Galleries VALUES (93, ' Olivia', 'Japan', 'Paris', '13CiFF1KcN');
INSERT INTO Galleries VALUES (94, 'Dr. Michael', 'Deutschland', 'PAR', 'oduEPINntK');
INSERT INTO Galleries VALUES (95, 'Dr. David', 'Deutschland', 'TYO', 'ZA*7MbEJr ');
INSERT INTO Galleries VALUES (96, 'Mr. Robert', 'Australia', 'PAR', 'fK05%FrxXJ');
INSERT INTO Galleries VALUES (97, 'Mrs. John', 'Deutschland', 'LON', '6AeZ1R7o8d');
INSERT INTO Galleries VALUES (98, 'Mrs. David', 'UK', 'PAR', 'hRUbU3HXCV');
INSERT INTO Galleries VALUES (99, 'Mrs. Alice', 'USA', 'NYC', 'n!yeHk6Znu');
INSERT INTO Galleries VALUES (100, 'Mrs. Olivia', 'America', 'Sydney', 'pRM@ew9R@m');
INSERT INTO Galleries VALUES (101, 'Dr. Alice', 'India', 'PAR', 'qB7dbQGPJU');
INSERT INTO Galleries VALUES (102, 'Mrs. Olivia', 'Deutschland', 'Tokyo', 'n8JVJry983');
INSERT INTO Galleries VALUES (103, 'Ms. Michael', 'Emirates', 'New York', '623V3skRx#');
INSERT INTO Galleries VALUES (104, ' Michael', 'Nippon', 'NYC', 'D*UmTjzHSS');
INSERT INTO Galleries VALUES (105, 'Mrs. Sophia', 'USA', 'Berlin', '#7&#ktAVcr');
INSERT INTO Galleries VALUES (106, 'Mr. David', 'Emirates', 'New York', 'F8z2O###an');
INSERT INTO Galleries VALUES (107, 'Mrs. Emily', 'India', 'DBX', 'cC 90RPTYN');
INSERT INTO Galleries VALUES (108, 'Dr. David', 'India', 'NYC', 'u&33a^bCMO');
INSERT INTO Galleries VALUES (109, 'Mr. Michael', 'UK', 'Mumbai', '#OJpjHRWVa');
INSERT INTO Galleries VALUES (110, 'Mr. Robert', 'Britain', 'SYD', 'brujJV9XEr');
INSERT INTO Galleries VALUES (111, 'Ms. Olivia', 'UAE', 'DBX', '#HbHp!%qdz');
INSERT INTO Galleries VALUES (112, 'Mr. Olivia', 'America', 'SYD', ' V@smkfIFZ');
INSERT INTO Galleries VALUES (113, 'Dr. Emily', 'Nippon', 'Berlin', 'SiZtUTXVYG');
INSERT INTO Galleries VALUES (114, 'Mrs. David', 'Emirates', 'LON', 'y$5iuzwexu');
INSERT INTO Galleries VALUES (115, 'Mrs. Olivia', 'America', 'DBX', 'f&vDv9y9IY');
INSERT INTO Galleries VALUES (116, 'Dr. Michael', 'Germany', 'PAR', '^%^FeOEhHb');
INSERT INTO Galleries VALUES (117, ' Sophia', 'UAE', 'BER', '^Hz7NE!!ri');
INSERT INTO Galleries VALUES (118, 'Ms. Emily', 'UAE', 'Mumbai', 'Tsf&oEozdL');
INSERT INTO Galleries VALUES (119, ' Robert', 'Japan', 'Berlin', 'ufMUc8Pic$');
INSERT INTO Galleries VALUES (120, 'Ms. Michael', 'Germany', 'BER', 'q5KCNbgPNn');
INSERT INTO Galleries VALUES (121, 'Ms. Olivia', 'Australia', 'BER', 'gM9 4rO^O8');
INSERT INTO Galleries VALUES (122, ' Robert', 'UK', 'TYO', 'bd0TbvPEg%');
INSERT INTO Galleries VALUES (123, 'Mr. John', 'Emirates', 'SYD', 'c4AW2$*k8 ');
INSERT INTO Galleries VALUES (124, 'Mrs. Emily', 'UAE', 'Paris', '3$&#w*5fmm');
INSERT INTO Galleries VALUES (125, ' Emily', 'America', 'TYO', '4InFPKnz0!');
INSERT INTO Galleries VALUES (126, 'Mrs. John', 'Germany', 'SYD', 'Iem!oiGhSv');
INSERT INTO Galleries VALUES (127, ' John', 'USA', 'Paris', 'j@PQn@L4xJ');
INSERT INTO Galleries VALUES (128, 'Mrs. Robert', 'Britain', 'Mumbai', '#CAk4Bixoq');
INSERT INTO Galleries VALUES (129, 'Mr. John', 'America', 'SYD', 'y&CN2hwee0');
INSERT INTO Galleries VALUES (130, 'Mr. Sophia', 'France', 'BOM', 'vs@Q!5QM^&');
INSERT INTO Galleries VALUES (131, ' David', 'Britain', 'London', 'z39#nnRE73');
INSERT INTO Galleries VALUES (132, 'Mr. Sophia', 'India', 'Tokyo', 'EhZp ^&xPe');
INSERT INTO Galleries VALUES (133, ' Olivia', 'India', 'Berlin', '^RzxU!hyfD');
INSERT INTO Galleries VALUES (134, 'Ms. Sophia', 'UAE', 'LON', 'eB0$AfH%X!');
INSERT INTO Galleries VALUES (135, 'Mrs. Olivia', 'Emirates', 'Sydney', 'y3jZ%TWmDo');
INSERT INTO Galleries VALUES (136, 'Ms. Emily', 'Deutschland', 'SYD', 'kNcUKHzI p');
INSERT INTO Galleries VALUES (137, 'Dr. Alice', 'Emirates', 'Tokyo', '!vxUrEUQ$Y');
INSERT INTO Galleries VALUES (138, 'Mrs. Sophia', 'Deutschland', 'TYO', 's6aEKUmB%A');
INSERT INTO Galleries VALUES (139, 'Mr. David', 'Germany', 'TYO', 'juHk9z3*7U');
INSERT INTO Galleries VALUES (140, 'Ms. Robert', 'Germany', 'Paris', 'doR*0smyF8');
INSERT INTO Galleries VALUES (141, 'Mrs. David', 'America', 'Berlin', 'c%V^o0tMtk');
INSERT INTO Galleries VALUES (142, ' Michael', 'Deutschland', 'PAR', '55zH#V87p7');
INSERT INTO Galleries VALUES (143, 'Ms. Emily', 'UAE', 'Sydney', 'ah5XqP6t*C');
INSERT INTO Galleries VALUES (144, 'Dr. Alice', 'India', 'DBX', 'jX#&1aJN6j');
INSERT INTO Galleries VALUES (145, ' David', 'UK', 'Paris', 'iUEuItPxKi');
INSERT INTO Galleries VALUES (146, 'Mr. John', 'DownUnder', 'BOM', '1ED ^qDEN^');
INSERT INTO Galleries VALUES (147, 'Mrs. Sophia', 'Emirates', 'Berlin', 'TA2hhG6G12');
INSERT INTO Galleries VALUES (148, ' Olivia', 'USA', 'LON', '#H5^ll%UhR');
INSERT INTO Galleries VALUES (149, 'Dr. Emily', 'USA', 'SYD', 'mygA!5@srN');
INSERT INTO Galleries VALUES (150, ' John', 'America', 'Tokyo', 'H*ppJC5J1R');
INSERT INTO Galleries VALUES (151, 'Dr. David', 'Nippon', 'Mumbai', '15x bM23YQ');
INSERT INTO Galleries VALUES (152, 'Dr. Robert', 'France', 'PAR', 'gqL#Tq$R#2');
INSERT INTO Galleries VALUES (153, 'Mrs. David', 'Emirates', 'LON', 'nNO*dKfMdE');
INSERT INTO Galleries VALUES (154, 'Dr. Emily', 'Nippon', 'Paris', 'BH6P^g%foH');
INSERT INTO Galleries VALUES (155, 'Ms. Olivia', 'Britain', 'NYC', '7dO2zbQ9vF');
INSERT INTO Galleries VALUES (156, 'Mr. Olivia', 'USA', 'SYD', '&hC9rwlc6N');
INSERT INTO Galleries VALUES (157, 'Mr. Emily', 'USA', 'Sydney', 'XJ3SJBsBmC');
INSERT INTO Galleries VALUES (158, 'Mrs. David', 'Japan', 'BER', 'd84h$7eFc#');
INSERT INTO Galleries VALUES (159, 'Ms. Alice', 'Deutschland', 'Mumbai', 'YE!*9haq1H');
INSERT INTO Galleries VALUES (160, 'Ms. Robert', 'Germany', 'DBX', 'ZXPng@^GiE');
INSERT INTO Galleries VALUES (161, ' Robert', 'Australia', 'Sydney', '$Jb4$LyFVo');
INSERT INTO Galleries VALUES (162, 'Ms. Alice', 'France', 'Sydney', 'a97!nF82y2');
INSERT INTO Galleries VALUES (163, 'Mrs. Emily', 'Nippon', 'PAR', '!gTh*Ehy%@');
INSERT INTO Galleries VALUES (164, 'Mrs. David', 'Emirates', 'London', '8eN!rJqN$q');
INSERT INTO Galleries VALUES (165, 'Dr. Olivia', 'Nippon', 'NYC', 'deWE E0%%H');
INSERT INTO Galleries VALUES (166, 'Dr. Michael', 'Japan', 'Sydney', ' YWrEsI7a^');
INSERT INTO Galleries VALUES (167, ' John', 'Australia', 'TYO', 'g&F2fxPl1H');
INSERT INTO Galleries VALUES (168, 'Ms. Emily', 'UK', 'Paris', '7TaUco**fi');
INSERT INTO Galleries VALUES (169, 'Dr. John', 'India', 'Dubai', 'kCAn8cRVP9');
INSERT INTO Galleries VALUES (170, 'Ms. Emily', 'India', 'Tokyo', 'x* KYJ&l8N');
INSERT INTO Galleries VALUES (171, 'Mrs. John', 'UK', 'SYD', 'X6cmCO&Kkz');
INSERT INTO Galleries VALUES (172, 'Mrs. Alice', 'India', 'Tokyo', 'AOJCj2FhOK');
INSERT INTO Galleries VALUES (173, 'Mrs. Emily', 'France', 'New York', 'wHH1MX32j2');
INSERT INTO Galleries VALUES (174, 'Dr. Emily', 'DownUnder', 'BOM', '9DE71X^I@3');
INSERT INTO Galleries VALUES (175, 'Mr. John', 'Emirates', 'DBX', 'CaoLL87p6J');
INSERT INTO Galleries VALUES (176, 'Ms. Emily', 'Australia', 'Dubai', 'JMy$aaQ4NR');
INSERT INTO Galleries VALUES (177, 'Dr. Michael', 'Deutschland', 'NYC', 'soX@2WeP1u');
INSERT INTO Galleries VALUES (178, 'Mrs. Alice', 'USA', 'Berlin', 'L*pLk2YN!i');
INSERT INTO Galleries VALUES (179, 'Dr. Emily', 'France', 'Sydney', 'uD^rQ#!hJh');
INSERT INTO Galleries VALUES (180, 'Ms. Alice', 'Britain', 'Sydney', 'l@!RzrXd&6');
INSERT INTO Galleries VALUES (181, 'Mr. Sophia', 'Japan', 'SYD', 'fINw5u1pgo');
INSERT INTO Galleries VALUES (182, ' Olivia', 'Emirates', 'Sydney', 'G@*EjD@Tn*');
INSERT INTO Galleries VALUES (183, ' Sophia', 'Australia', 'BER', '8TLG7KS3D$');
INSERT INTO Galleries VALUES (184, ' Alice', 'America', 'TYO', 'b53 ELSdij');
INSERT INTO Galleries VALUES (185, 'Mr. Emily', 'USA', 'Tokyo', 'hlQcQ7114%');
INSERT INTO Galleries VALUES (186, 'Mrs. Sophia', 'USA', 'Tokyo', 'PvUQb3k0M5');
INSERT INTO Galleries VALUES (187, ' Olivia', 'India', 'NYC', 'DC3a c$E8X');
INSERT INTO Galleries VALUES (188, 'Mr. Robert', 'UK', 'TYO', '2z7LC&8Z^1');
INSERT INTO Galleries VALUES (189, ' Olivia', 'Nippon', 'NYC', 'u1h!FN4drB');
INSERT INTO Galleries VALUES (190, 'Mrs. Sophia', 'Deutschland', 'SYD', '6g Jcx2@#o');
INSERT INTO Galleries VALUES (191, ' Alice', 'France', 'SYD', 'Hexd5J#kLR');
INSERT INTO Galleries VALUES (192, ' Emily', 'India', 'Tokyo', '80kyzOs7lj');
INSERT INTO Galleries VALUES (193, 'Dr. Michael', 'Japan', 'Dubai', '& &z0Od7o8');
INSERT INTO Galleries VALUES (194, 'Mr. Sophia', 'Japan', 'Tokyo', '@!FG%0kJU0');
INSERT INTO Galleries VALUES (195, 'Mr. Robert', 'Japan', 'Paris', 'U1!TV3xsVj');
INSERT INTO Galleries VALUES (196, ' Olivia', 'DownUnder', 'Dubai', '%zIprvP!rs');
INSERT INTO Galleries VALUES (197, 'Mrs. Olivia', 'DownUnder', 'Tokyo', 'zwofvSguZs');
INSERT INTO Galleries VALUES (198, ' David', 'Germany', 'Mumbai', ' lqws##yll');
INSERT INTO Galleries VALUES (199, 'Mr. John', 'UAE', 'Tokyo', 'D4IFny#OL*');
INSERT INTO Galleries VALUES (200, 'Mrs. Emily', 'Deutschland', 'NYC', '@zwlf%U8ux');
