Use ArtExhibitionsDB
go
INSERT INTO Staff VALUES (1, 'Mrs. Olivia', 'kQgVlX17@R', 'Emirates', 'TYO');
INSERT INTO Staff VALUES (2, 'Dr. Sophia', 'O#62x#mac2', 'USA', 'Tokyo');
INSERT INTO Staff VALUES (3, 'Dr. John', 'ywQk%X2TKg', 'Nippon', 'Mumbai');
INSERT INTO Staff VALUES (4, 'Dr. David', '^qzJ6mQTQO', 'UK', 'TYO');
INSERT INTO Staff VALUES (5, 'Mrs. Sophia', '^^dA#sBgbE', 'DownUnder', 'Tokyo');
INSERT INTO Staff VALUES (6, 'Ms. John', 'lgQ4Nkw3!y', 'Britain', 'Paris');
INSERT INTO Staff VALUES (7, 'Ms. David', 'ETF@cccd8w', 'Emirates', 'London');
INSERT INTO Staff VALUES (8, ' Olivia', 'B2JSfnoc2%', 'Australia', 'LON');
INSERT INTO Staff VALUES (9, 'Dr. Olivia', '*66JHBwOyU', 'Japan', 'TYO');
INSERT INTO Staff VALUES (10, 'Ms. Sophia', '1fRud&6W7&', 'Emirates', 'TYO');
INSERT INTO Staff VALUES (11, 'Mrs. Michael', '! m2w8*sc6', 'USA', 'Dubai');
INSERT INTO Staff VALUES (12, 'Mrs. John', 'o2ACZbxkNp', 'America', 'Paris');
INSERT INTO Staff VALUES (13, 'Mrs. Robert', '2#OIVlVBX1', 'UK', 'SYD');
INSERT INTO Staff VALUES (14, 'Ms. David', '1hBl59qa^H', 'France', 'Paris');
INSERT INTO Staff VALUES (15, ' Michael', 'gwcL8WqF#p', 'France', 'Berlin');
INSERT INTO Staff VALUES (16, 'Mrs. Olivia', '87pCL27CFy', 'India', 'TYO');
INSERT INTO Staff VALUES (17, ' Michael', 'g1Rk13xy!9', 'Nippon', 'Sydney');
INSERT INTO Staff VALUES (18, 'Mrs. Michael', 'Bnck0PKNmv', 'UK', 'NYC');
INSERT INTO Staff VALUES (19, 'Mrs. Michael', 'Im9YOwErML', 'UAE', 'Sydney');
INSERT INTO Staff VALUES (20, 'Dr. Alice', '4Ob&Bz4ePV', 'Britain', 'Berlin');
INSERT INTO Staff VALUES (21, ' Michael', '&U765H$T5V', 'America', 'BER');
INSERT INTO Staff VALUES (22, ' David', 'YsglsHisj$', 'India', 'BER');
INSERT INTO Staff VALUES (23, 'Mrs. Sophia', 'C75^PLJ1gA', 'Australia', 'London');
INSERT INTO Staff VALUES (24, 'Dr. Olivia', 'A&qMAM^7n$', 'Japan', 'BER');
INSERT INTO Staff VALUES (25, ' David', '4RZuK3NScg', 'Nippon', 'Mumbai');
INSERT INTO Staff VALUES (26, 'Ms. Olivia', 'ps7AgSamCD', 'Deutschland', 'London');
INSERT INTO Staff VALUES (27, 'Mr. David', 'cPGW#rSwu!', 'Britain', 'New York');
INSERT INTO Staff VALUES (28, ' Michael', 'hjZ*Tw$ E%', 'Japan', 'DBX');
INSERT INTO Staff VALUES (29, ' Robert', '*O6gTgVwQb', 'Emirates', 'LON');
INSERT INTO Staff VALUES (30, 'Dr. Robert', 'S q%pKYNyL', 'Nippon', 'New York');
INSERT INTO Staff VALUES (31, ' David', '4G 2unHbDr', 'America', 'PAR');
INSERT INTO Staff VALUES (32, 'Dr. Alice', 'AwxiUrGgAc', 'India', 'New York');
INSERT INTO Staff VALUES (33, 'Mrs. Sophia', 'H@ xe5gd^T', 'India', 'LON');
INSERT INTO Staff VALUES (34, 'Mr. David', 'WPbhv7pJrC', 'Australia', 'SYD');
INSERT INTO Staff VALUES (35, 'Ms. Alice', 'd2OL0h!2fn', 'Australia', 'SYD');
INSERT INTO Staff VALUES (36, 'Mrs. David', 'tjJ6ITAtVt', 'India', 'London');
INSERT INTO Staff VALUES (37, 'Ms. Sophia', 'RK25aflx&d', 'Germany', 'SYD');
INSERT INTO Staff VALUES (38, 'Mr. Robert', 'mUTtU^Bi@@', 'India', 'PAR');
INSERT INTO Staff VALUES (39, 'Dr. Alice', 'q BKkVB4 v', 'Australia', 'BER');
INSERT INTO Staff VALUES (40, 'Ms. Sophia', 'R2qYfLfY7d', 'Nippon', 'Paris');
INSERT INTO Staff VALUES (41, 'Mrs. Sophia', 'Meq*fsR5vc', 'America', 'London');
INSERT INTO Staff VALUES (42, 'Ms. Alice', 'Rn$qunI^z8', 'France', 'Tokyo');
INSERT INTO Staff VALUES (43, 'Dr. Emily', 'dxy&Q^SWwh', 'India', 'Sydney');
INSERT INTO Staff VALUES (44, 'Mrs. Olivia', '$NkQ$jm0El', 'Nippon', 'LON');
INSERT INTO Staff VALUES (45, 'Mrs. Olivia', 'bu8%1nSIT5', 'France', 'BER');
INSERT INTO Staff VALUES (46, 'Ms. Sophia', 'pLLm!Oj$&M', 'UK', 'TYO');
INSERT INTO Staff VALUES (47, 'Mr. Emily', 'p$4RYE34*g', 'Britain', 'SYD');
INSERT INTO Staff VALUES (48, 'Mrs. Olivia', 'nIa4vQBUwr', 'USA', 'DBX');
INSERT INTO Staff VALUES (49, ' David', '4qP5n&yJ##', 'Germany', 'Paris');
INSERT INTO Staff VALUES (50, 'Ms. Emily', 'NbGPqP0Gsk', 'France', 'Paris');
INSERT INTO Staff VALUES (51, 'Ms. John', '3qCmDRi4F@', 'Australia', 'NYC');
INSERT INTO Staff VALUES (52, 'Mr. Sophia', 'YIsrVPm9w9', 'DownUnder', 'SYD');
INSERT INTO Staff VALUES (53, 'Ms. David', '445JRJp$t^', 'India', 'Dubai');
INSERT INTO Staff VALUES (54, ' Alice', 'Db7X4Oqlvb', 'UK', 'BOM');
INSERT INTO Staff VALUES (55, 'Dr. Robert', 'FN!egtIitT', 'France', 'Tokyo');
INSERT INTO Staff VALUES (56, 'Mrs. Emily', 'K82d!Dbr2g', 'India', 'Sydney');
INSERT INTO Staff VALUES (57, 'Ms. Robert', 'njx%yXJru&', 'Emirates', 'BOM');
INSERT INTO Staff VALUES (58, 'Dr. David', 'yj81 zlCxE', 'France', 'NYC');
INSERT INTO Staff VALUES (59, 'Ms. David', 'nXkQbDn7Db', 'Australia', 'PAR');
INSERT INTO Staff VALUES (60, 'Mrs. Alice', 'yTjv*F&k3j', 'India', 'BER');
INSERT INTO Staff VALUES (61, 'Mr. John', 'MeGQLJpJbd', 'Australia', 'LON');
INSERT INTO Staff VALUES (62, 'Dr. Michael', 'gvlr$XShI&', 'Deutschland', 'London');
INSERT INTO Staff VALUES (63, ' John', '*#8UwoFQZs', 'USA', 'DBX');
INSERT INTO Staff VALUES (64, 'Mr. Alice', 'vQm9HXhf8o', 'Germany', 'PAR');
INSERT INTO Staff VALUES (65, 'Mr. Emily', 'Ezw4Pl9bei', 'UAE', 'New York');
INSERT INTO Staff VALUES (66, 'Ms. Alice', '4$r#4A 5oM', 'India', 'PAR');
INSERT INTO Staff VALUES (67, 'Ms. David', '5wCGEBp6kJ', 'USA', 'BER');
INSERT INTO Staff VALUES (68, 'Ms. David', 'ZMur2R85cB', 'Emirates', 'Sydney');
INSERT INTO Staff VALUES (69, 'Dr. Michael', '@d8W*6R5 b', 'Britain', 'New York');
INSERT INTO Staff VALUES (70, 'Ms. David', '!RtGfQkRyP', 'Britain', 'PAR');
INSERT INTO Staff VALUES (71, ' Sophia', 'mQG67CbRO6', 'Australia', 'SYD');
INSERT INTO Staff VALUES (72, 'Ms. Emily', 'Zh5gjxp$vP', 'DownUnder', 'BOM');
INSERT INTO Staff VALUES (73, 'Mr. Michael', 'E1M#PWMYih', 'America', 'NYC');
INSERT INTO Staff VALUES (74, 'Dr. David', 'Pyt0XFsNdE', 'India', 'BOM');
INSERT INTO Staff VALUES (75, 'Ms. Emily', '2 eK*HJE4n', 'Britain', 'DBX');
INSERT INTO Staff VALUES (76, 'Mrs. John', 'WnAAA hxGW', 'USA', 'BER');
INSERT INTO Staff VALUES (77, ' Robert', 'NEVodNXoLx', 'USA', 'NYC');
INSERT INTO Staff VALUES (78, ' Alice', 'OcMBL7!ejD', 'India', 'Dubai');
INSERT INTO Staff VALUES (79, 'Mrs. Alice', 'gM9Z33mR1J', 'Britain', 'Mumbai');
INSERT INTO Staff VALUES (80, 'Dr. David', 'zvC0kFvX4y', 'Deutschland', 'New York');
INSERT INTO Staff VALUES (81, 'Mrs. Alice', '!Kb *Bqpos', 'Japan', 'LON');
INSERT INTO Staff VALUES (82, 'Dr. Olivia', '5gyd# kvol', 'USA', 'Paris');
INSERT INTO Staff VALUES (83, 'Mr. Alice', 'zHKJq9mqa!', 'Australia', 'BER');
INSERT INTO Staff VALUES (84, 'Mr. John', 'v LkEyUob#', 'USA', 'London');
INSERT INTO Staff VALUES (85, 'Mrs. David', 'u3V@rNNnB2', 'Nippon', 'Dubai');
INSERT INTO Staff VALUES (86, 'Dr. Sophia', 'M*3ftF^HOL', 'Australia', 'Mumbai');
INSERT INTO Staff VALUES (87, ' Emily', '9Wy70W5g69', 'Germany', 'New York');
INSERT INTO Staff VALUES (88, 'Mrs. Alice', 'FuNZ1d77li', 'Germany', 'London');
INSERT INTO Staff VALUES (89, 'Mrs. David', '%p7^&%tGZu', 'France', 'Mumbai');
INSERT INTO Staff VALUES (90, 'Ms. Sophia', '!HMtpxitgo', 'Japan', 'Berlin');
INSERT INTO Staff VALUES (91, 'Dr. Robert', 'P&73t$KbYF', 'France', 'New York');
INSERT INTO Staff VALUES (92, 'Mr. Emily', 'P KF06Vymj', 'Japan', 'SYD');
INSERT INTO Staff VALUES (93, 'Mrs. Olivia', '^GQXyGilv&', 'India', 'DBX');
INSERT INTO Staff VALUES (94, 'Mrs. Robert', 'XQpUnw3H$g', 'DownUnder', 'BER');
INSERT INTO Staff VALUES (95, 'Mrs. Sophia', '@KHoX UAwG', 'Nippon', 'Tokyo');
INSERT INTO Staff VALUES (96, 'Mrs. Alice', ' oCB0 IUQm', 'Emirates', 'Dubai');
INSERT INTO Staff VALUES (97, 'Mr. Alice', '2wZyx9Q2OH', 'Germany', 'Dubai');
INSERT INTO Staff VALUES (98, 'Dr. Robert', 'rhpj81c^Ve', 'Deutschland', 'TYO');
INSERT INTO Staff VALUES (99, 'Dr. David', '8fW7r8tL4h', 'UAE', 'PAR');
INSERT INTO Staff VALUES (100, 'Mr. John', 'GT!qgK2@XY', 'Japan', 'Paris');
INSERT INTO Staff VALUES (101, 'Mr. Robert', '^Mwipz2Xz5', 'France', 'Paris');
INSERT INTO Staff VALUES (102, ' Alice', 'r I0P2Ej0Q', 'Britain', 'SYD');
INSERT INTO Staff VALUES (103, 'Ms. Olivia', 'Ul3ggBfX!R', 'Germany', 'Berlin');
INSERT INTO Staff VALUES (104, 'Ms. Alice', 'JgH$cIbw3Y', 'Deutschland', 'BER');
INSERT INTO Staff VALUES (105, 'Ms. Michael', 'Pg8essmyx@', 'UAE', 'BER');
INSERT INTO Staff VALUES (106, ' David', 'aAkl!0eGsd', 'France', 'BOM');
INSERT INTO Staff VALUES (107, ' David', '!$DA03 aXw', 'Emirates', 'SYD');
INSERT INTO Staff VALUES (108, 'Mrs. John', 'D*YRjCxkYO', 'America', 'New York');
INSERT INTO Staff VALUES (109, 'Mrs. Michael', 'ZNLvJdc8v^', 'UK', 'Sydney');
INSERT INTO Staff VALUES (110, 'Dr. John', 'piLBTs^MfA', 'Japan', 'Sydney');
INSERT INTO Staff VALUES (111, 'Mrs. Olivia', 'qb&N3fNKZ2', 'UAE', 'Paris');
INSERT INTO Staff VALUES (112, 'Mr. Sophia', '*GlzR9YG!9', 'UAE', 'Dubai');
INSERT INTO Staff VALUES (113, 'Ms. Robert', 'zaLYMMJeGb', 'Nippon', 'DBX');
INSERT INTO Staff VALUES (114, 'Mr. Alice', 'Zy^xNrYZ3h', 'USA', 'PAR');
INSERT INTO Staff VALUES (115, ' John', '2#k4 59BdT', 'UK', 'Sydney');
INSERT INTO Staff VALUES (116, 'Ms. Olivia', 'LEfutImT1z', 'Britain', 'BER');
INSERT INTO Staff VALUES (117, ' Sophia', '#EEzzY2xfl', 'Nippon', 'TYO');
INSERT INTO Staff VALUES (118, 'Mr. Alice', '$wwcBr@cq!', 'Germany', 'New York');
INSERT INTO Staff VALUES (119, 'Dr. Robert', 'i7wwJv6$o1', 'America', 'DBX');
INSERT INTO Staff VALUES (120, ' Alice', 'vlxPjHjPZL', 'UK', 'PAR');
INSERT INTO Staff VALUES (121, 'Mrs. David', 'EYE69uAf@3', 'UAE', 'Berlin');
INSERT INTO Staff VALUES (122, 'Mrs. Olivia', 'T$N&qyTuz@', 'USA', 'Berlin');
INSERT INTO Staff VALUES (123, 'Ms. Emily', 'd0b86W5zMq', 'USA', 'NYC');
INSERT INTO Staff VALUES (124, 'Ms. Sophia', '9eQJoA^a&5', 'Britain', 'Sydney');
INSERT INTO Staff VALUES (125, 'Mr. John', 'h9W6zTxWXs', 'Emirates', 'DBX');
INSERT INTO Staff VALUES (126, 'Mrs. Robert', 'N T5TDZNF1', 'Britain', 'BER');
INSERT INTO Staff VALUES (127, 'Dr. Michael', 'zuanFoBroA', 'UK', 'New York');
INSERT INTO Staff VALUES (128, 'Dr. Michael', 'C*GivPm2#z', 'UK', 'NYC');
INSERT INTO Staff VALUES (129, 'Mrs. Alice', '!Vot03vUGk', 'Japan', 'TYO');
INSERT INTO Staff VALUES (130, 'Mr. Sophia', 'ncIR#L8Ij9', 'UK', 'SYD');
INSERT INTO Staff VALUES (131, 'Mrs. Robert', 'kGAn7gfik&', 'Britain', 'NYC');
INSERT INTO Staff VALUES (132, 'Ms. David', 'I!yAzZriMt', 'India', 'DBX');
INSERT INTO Staff VALUES (133, ' Alice', 'gv#wEPLFp6', 'Britain', 'Berlin');
INSERT INTO Staff VALUES (134, 'Dr. David', 'UQbXn revm', 'Japan', 'Berlin');
INSERT INTO Staff VALUES (135, 'Dr. Sophia', 'EtSIvIOLSY', 'Germany', 'TYO');
INSERT INTO Staff VALUES (136, 'Ms. Olivia', 'DdlJAfydT ', 'India', 'LON');
INSERT INTO Staff VALUES (137, 'Dr. John', 'JHPNh6olbF', 'India', 'NYC');
INSERT INTO Staff VALUES (138, 'Mrs. Michael', 'UqU%yZL43t', 'America', 'DBX');
INSERT INTO Staff VALUES (139, 'Ms. Emily', 'UV1%u!1yKr', 'UK', 'BOM');
INSERT INTO Staff VALUES (140, 'Dr. Sophia', '*yo7 qUwhd', 'UAE', 'London');
INSERT INTO Staff VALUES (141, 'Ms. David', 'YJE!dpoii4', 'Germany', 'LON');
INSERT INTO Staff VALUES (142, ' Michael', '0u#67lr5$G', 'France', 'PAR');
INSERT INTO Staff VALUES (143, 'Mr. David', '*9NlmlOFvJ', 'Deutschland', 'LON');
INSERT INTO Staff VALUES (144, 'Ms. Emily', '51dKf6t&XR', 'America', 'Sydney');
INSERT INTO Staff VALUES (145, 'Mr. Robert', '11KQmMOqKJ', 'Deutschland', 'LON');
INSERT INTO Staff VALUES (146, 'Mrs. Emily', 'pB00dPQanV', 'Nippon', 'New York');
INSERT INTO Staff VALUES (147, 'Mrs. Emily', '44tY5FVw5v', 'UAE', 'TYO');
INSERT INTO Staff VALUES (148, 'Ms. Robert', 'olqXGl7$tf', 'France', 'Mumbai');
INSERT INTO Staff VALUES (149, 'Mrs. Robert', 'H%W7LqplpH', 'USA', 'NYC');
INSERT INTO Staff VALUES (150, 'Mr. Emily', 'q5$d3X7^k^', 'Nippon', 'BER');
INSERT INTO Staff VALUES (151, ' Michael', '4TNMTMxm9c', 'Japan', 'BOM');
INSERT INTO Staff VALUES (152, 'Mrs. Olivia', 'gpN4^^!6NU', 'UAE', 'Sydney');
INSERT INTO Staff VALUES (153, 'Ms. Robert', '^&J9BxZYaf', 'Japan', 'NYC');
INSERT INTO Staff VALUES (154, 'Dr. Sophia', 'JiMyf*bk1Y', 'Deutschland', 'BOM');
INSERT INTO Staff VALUES (155, ' Emily', 'prkq@fr*&4', 'France', 'Berlin');
INSERT INTO Staff VALUES (156, 'Mrs. Alice', 'djvTYlI3DD', 'Japan', 'LON');
INSERT INTO Staff VALUES (157, 'Dr. Sophia', 'tSHk^LGkr6', 'India', 'Tokyo');
INSERT INTO Staff VALUES (158, ' Robert', 'So1PBC@gYB', 'Deutschland', 'Mumbai');
INSERT INTO Staff VALUES (159, 'Dr. Alice', 'RM rwoNzlI', 'India', 'Paris');
INSERT INTO Staff VALUES (160, 'Mrs. John', '6nSW%@g&HI', 'Nippon', 'BOM');
INSERT INTO Staff VALUES (161, 'Dr. Michael', 'Vxm8jQ!TC#', 'USA', 'SYD');
INSERT INTO Staff VALUES (162, 'Mrs. Michael', 'mb&P@0nsTr', 'Australia', 'SYD');
INSERT INTO Staff VALUES (163, 'Mr. Robert', 'vk0puKkf!J', 'India', 'New York');
INSERT INTO Staff VALUES (164, 'Dr. Emily', 'IGij9NdX%S', 'DownUnder', 'Paris');
INSERT INTO Staff VALUES (165, 'Mrs. Alice', 'jnu!yKsJT!', 'Nippon', 'Mumbai');
INSERT INTO Staff VALUES (166, ' John', '^yV$WK1bE&', 'Emirates', 'Paris');
INSERT INTO Staff VALUES (167, 'Dr. Robert', 'ZEh56&dXoj', 'America', 'TYO');
INSERT INTO Staff VALUES (168, 'Dr. Olivia', 'Tr^pCS1Yz%', 'Japan', 'BOM');
INSERT INTO Staff VALUES (169, 'Mrs. Emily', 'TVCO6l&4l1', 'America', 'London');
INSERT INTO Staff VALUES (170, 'Mrs. Alice', 'UU39gKDlJu', 'Deutschland', 'Sydney');
INSERT INTO Staff VALUES (171, 'Dr. Emily', 'bHu8OSoNlP', 'Japan', 'DBX');
INSERT INTO Staff VALUES (172, 'Ms. Alice', 'E!M%ZCfv&X', 'Nippon', 'Paris');
INSERT INTO Staff VALUES (173, 'Mr. Michael', 'q#mW2 KP20', 'Nippon', 'Tokyo');
INSERT INTO Staff VALUES (174, 'Mrs. John', 'C6UZB8CgUc', 'Britain', 'BOM');
INSERT INTO Staff VALUES (175, 'Dr. Alice', 'Amw% c9V%o', 'Germany', 'TYO');
INSERT INTO Staff VALUES (176, 'Mr. Emily', '3kxxgEZKKa', 'Britain', 'LON');
INSERT INTO Staff VALUES (177, ' Sophia', 'zCJ*tP6L0@', 'Deutschland', 'TYO');
INSERT INTO Staff VALUES (178, 'Mr. Alice', 'pzeOXSwsA!', 'UK', 'TYO');
INSERT INTO Staff VALUES (179, 'Ms. David', 'akPdN@em#y', 'Australia', 'LON');
INSERT INTO Staff VALUES (180, 'Dr. Emily', 'dUd1@Ziq@%', 'India', 'NYC');
INSERT INTO Staff VALUES (181, ' John', 'sN%uF7x*oL', 'Japan', 'Tokyo');
INSERT INTO Staff VALUES (182, 'Ms. Olivia', '%ch8rbbFp5', 'Australia', 'BER');
INSERT INTO Staff VALUES (183, ' Emily', 'Nl7jqerlWO', 'UAE', 'NYC');
INSERT INTO Staff VALUES (184, 'Mr. Olivia', 'nJyo7ngSzc', 'Japan', 'SYD');
INSERT INTO Staff VALUES (185, 'Mrs. Olivia', '6$P5^#n2q&', 'India', 'PAR');
INSERT INTO Staff VALUES (186, 'Mrs. Michael', 'inbiI6P#B5', 'Deutschland', 'TYO');
INSERT INTO Staff VALUES (187, 'Dr. Olivia', 'laC8EwzDs^', 'Japan', 'BOM');
INSERT INTO Staff VALUES (188, ' Robert', 'mvDbiaElLR', 'UK', 'Sydney');
INSERT INTO Staff VALUES (189, 'Dr. Michael', 'SU07ZwKoCA', 'Germany', 'Sydney');
INSERT INTO Staff VALUES (190, 'Mr. Michael', 'Sw8BykDn@K', 'Britain', 'SYD');
INSERT INTO Staff VALUES (191, 'Ms. Emily', 'i p^2wqc^5', 'USA', 'TYO');
INSERT INTO Staff VALUES (192, 'Mrs. David', 'UMjSTxk&sq', 'Emirates', 'BOM');
INSERT INTO Staff VALUES (193, 'Mrs. Robert', 'Z79bAF@EPc', 'India', 'Dubai');
INSERT INTO Staff VALUES (194, 'Mr. John', 'MbM7ojsXk7', 'Japan', 'BER');
INSERT INTO Staff VALUES (195, 'Mrs. Robert', 'LjgA%dO#xx', 'Germany', 'TYO');
INSERT INTO Staff VALUES (196, ' Robert', 'tfT8xQ04D7', 'UK', 'New York');
INSERT INTO Staff VALUES (197, ' Michael', 'gHue &8ax1', 'Nippon', 'LON');
INSERT INTO Staff VALUES (198, 'Mr. Michael', 'jsDFFD0W33', 'Germany', 'TYO');
INSERT INTO Staff VALUES (199, ' Olivia', 'K2y6iKhwe4', 'Britain', 'BOM');
INSERT INTO Staff VALUES (200, 'Dr. David', 'nK9&hgulMr', 'UK', 'London');
